name: Health Check

on:
  schedule:
    - cron:  '1 * * * 7'

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: https://pokedex-test-1422.herokuapp.com/health
        max-attempts: 3
        retry-delay: 5s