name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests 
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
  deploy:
    env:
       COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
    needs: simple_deployment_pipeline
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Check commit messages for skip tag
        run: echo "Skipping!"
        if: ${{github.event_name == 'push' && contains(join(COMMIT_MESSAGES), '#skip') }}
      - name: Conditions event name is push
        run: echo github.event_name == 'push'
      - name: Commit messages contains skip
        run: echo ${{contains(join(COMMIT_MESSAGES), '#skip')}}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: heroku deployment 
        uses: akhileshns/heroku-deploy@v3.8.9
        if: ${{ github.event_name == 'push' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'pokedex-test-1422'
          heroku_email: 'lahtinen.jaakko@gmail.com'
          healthcheck: "https://pokedex-test-1422.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true